### ISSUE TITLE
Where  is the splits/kitti_archives_to_download.txt ?

### ISSUE THREAD

**Issue by Tony-Hou** [ldkong1205/RoboDepth#1]
wget -i splits/kitti_archives_to_download.txt -P kitti_data/

**Comment by ldkong1205** [comment]
Hi @Tony-Hou, sorry for the misunderstanding and thank you for your notice. The file `kitti_archives_to_download.txt` has just been added to the Repo, under the `splits` folder.

**Comment by ldkong1205** [comment]
I am closing this issue now. Feel free to open a new one if you have any other questions 😄

**Comment by Tony-Hou** [comment]
Thank you!
