### ISSUE TITLE
track1 evaluate

### ISSUE THREAD

**Issue by Han-SHS** [ldkong1205/RoboDepth#11]
Hi @ldkong1205， we tried to upload our model to robodepth track1 web，there is something error in the upload

`WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
Traceback (most recent call last):
  File "/tmp/codalab/tmpO_xDM7/run/program/evaluate.py", line 55, in 
    pred_disps = np.load(submit_path)
  File "/opt/conda/lib/python3.9/site-packages/numpy/lib/npyio.py", line 430, in load
    return format.read_array(fid, allow_pickle=allow_pickle,
  File "/opt/conda/lib/python3.9/site-packages/numpy/lib/format.py", line 742, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False` 

we uploda our model to this web so many times before this error，if  our disp.zip have something wrong need to revise please tall me at once.

Thanks, best wishes!

**Comment by Han-SHS** [comment]
expect the above question，I have another thing want to know， can  we use the post process into our model?

**Comment by ldkong1205** [comment]
Hi @Han-SHS, thanks for your interest in our competition!

Regarding your question: Could you double-check that you have correctly followed the instructions? For example, for track 1 you will need to first save the predictions into `.npy` format and then manually compress the file into a `.zip` file:

```
output_path = os.path.join(opt.save_pred_path, "disp.npy")
np.save(output_path, pred_disps)
```

```
zip disp.zip disp.npy
```

You should also check whether the complete predictions are saved or not.

For the post-processing: Can you elaborate more details on this? What kind of post-processing technique do you want to use?

**Comment by Han-SHS** [comment]
HI @ldkong1205 

we check our model again and again, we upload other disp.zip to verify our assessment method，the result show that our  disp.zip generation method is right and the disp.zip we upload before this is all right. this disp as same as before disp in the weights.

For the post-processing: for eample Thresholding, Median Filtering, and Normalization ，those methods alway be used in the MDE.

**Comment by ldkong1205** [comment]
Hi @Han-SHS, thanks for your information!

It is a bit strange because we did not encounter an error like this one before. Perhaps you can try to check if you are using `np.savez` instead of `np.save`. Otherwise, we cannot provide extra cues on this problem. One possible way is to ask other participants whether they met this error before.

For the mentioned post-processing techniques: The listed examples are common ones in MDE and you are free to use in this competition ~

**Comment by ldkong1205** [comment]
Please also search for previous issues, just to see if there are any similar ones as yours.

**Comment by Han-SHS** [comment]
I have read other questions, but there is not the same problem as ours. The closest one is a size problem, but it is not the same as ours. We see an error message indicating that it is the loading problem of the list. So it is very important for us that you review your evaluation documents carefully.

**Comment by ldkong1205** [comment]
Hi @Han-SHS, thanks for the follow-ups.

I attach the snippet of the scoring program that we are using for loading files:
```
# get the ground truth point clouds
truth_path = os.path.join(truth_dir, "gt.npy")
gt_depths = np.load(truth_path, allow_pickle=True)

print("GT loaded.")

# get the submitted point clouds
submit_path = os.path.join(submit_dir, "disp.npy")
pred_disps = np.load(submit_path)

print("Pred loaded.")

assert len(pred_disps) == len(gt_depths)
```

You can have a look and check if you miss anything, e.g., file name and suffix. Note that the submitted file must meet the exact same name in order to successfully load it.

You should also check your saving command. As your error message says, it is something related `np.load`.

**Comment by Han-SHS** [comment]
I have found that there were issues with our evaluation code, but we have made the necessary modifications and are now able to generate the correct files. Thank you for your response, and we apologize for any inconvenience caused.

**Comment by ldkong1205** [comment]
Hi @Han-SHS, glad to hear that you have solved your problem!

Feel free to open a new issue if you encounter any other problems ~
