### ISSUE TITLE
the download link for kitti_c is not working

### ISSUE THREAD

**Issue by Han-SHS** [ldkong1205/RoboDepth#12]
We have noticed that the download link for kitti_c is not working. Since the previously downloaded kitti_c has some issues, we need to re-download it for model evaluation. Could you please check the relevant website?

best wish

**Comment by ldkong1205** [comment]
Hi @Han-SHS, thanks for your information!

We have updated the link in the document. You can now download KITTI-C via the following link:
https://drive.google.com/file/d/1Ohyh8CN0ZS7gc_9l4cIwX4j97rIRwADa/view?usp=sharing

Alternatively, you can download this dataset via the following command:
```
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1Ohyh8CN0ZS7gc_9l4cIwX4j97rIRwADa' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1Ohyh8CN0ZS7gc_9l4cIwX4j97rIRwADa" -O kitti_c.zip && rm -rf /tmp/cookies.txt
```

Let us know if the above works for you. Thanks!
