### ISSUE TITLE
[Competition] Question

### ISSUE THREAD

**Issue by ZephyRUXS** [ldkong1205/RoboDepth#2]

**Comment by ZephyRUXS** [comment]
Are there any instruction about this competition of self-supervised track? I cannot find anything in the readme.md and competition.md

**Comment by ldkong1205** [comment]
> Are there any instruction about this competition of self-supervised track? I cannot find anything in the readme.md and competition.md

Hi @ZephyRUXS, thank you for your interest in this competition! The detailed instructions for participating Track 1 will be available by tomorrow. We will include the data preparation, training and evaluation instructions, and rules. We will settle these things as soon as possible and let you know once they are ready. Thanks again!

**Comment by ZephyRUXS** [comment]
> > Are there any instruction about this competition of self-supervised track? I cannot find anything in the readme.md and competition.md
> 
> Hi @ZephyRUXS, thank you for your interest in this competition! The detailed instructions for participating Track 1 will be available by tomorrow. We will include the data preparation, training and evaluation instructions, and rules. We will settle these things as soon as possible and let you know once they are ready. Thanks again!

Thank you to answer my question and organize this competition. I will check details tomorrow.

**Comment by ldkong1205** [comment]
Hi @ZephyRUXS, we have added details for data preparation and submission, please see this page:
https://github.com/ldkong1205/RoboDepth/blob/main/competition/README.md

Please let us know if you have any questions or concerns. Your feedback would be of great help for us to improve the quality of this competition. Thanks a lot!

**Comment by ZephyRUXS** [comment]
Dear ldkong:Thanks, I have checked the details. According to the competition details, we only can use raw Kitti as training dataset?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Lingdong ***@***.***&gt;; 
发送时间: 2023年1月5日(星期四) 上午9:23
收件人: ***@***.***&gt;; 
抄送: "???Jin ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ldkong1205/RoboDepth] Question (Issue #2)





 
Hi @ZephyRUXS, we have added details for data preparation and submission, please see this page:
 https://github.com/ldkong1205/RoboDepth/blob/main/competition/README.md
 
Please let us know if you have any questions or concerns. Your feedback would be of great help for us to improve the quality of this competition. Thanks a lot!

**Comment by ldkong1205** [comment]
> Dear ldkong:Thanks, I have checked the details. According to the competition details, we only can use raw Kitti as training dataset?

Hi @ZephyRUXS, you are correct! To ensure a fair comparison, all participants in Track 1 are only allowed to use the images from the raw KITTI dataset as the training dataset.

Recall that the theme of this competition is to explore novel architectures and techniques that are robust against common corruptions. Therefore, all participants should adopt the same training/evaluation data and compare each other on top of this.

Please let us know if you have any other questions or concerns. Thanks!

**Comment by ZephyRUXS** [comment]
Hi ldkong:Thanks, I got it.
Sincerely
Qi




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Lingdong ***@***.***&gt;; 
发送时间: 2023年1月5日(星期四) 下午3:01
收件人: ***@***.***&gt;; 
抄送: "???Jin ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ldkong1205/RoboDepth] [Competition] Question (Issue #2)





  
Dear ldkong:Thanks, I have checked the details. According to the competition details, we only can use raw Kitti as training dataset?
  
Hi @ZephyRUXS, you are correct! To ensure a fair comparison, all participants in Track 1 are only allowed to use the images from the raw KITTI dataset as the training dataset.
 
Recall that the theme of this competition is to explore novel architectures and techniques that are robust against common corruptions. Therefore, all participants should adopt the same training/evaluation data and compare each other on top of this.
 
Please let us know if you have any other questions or concerns. Thanks!

**Comment by ldkong1205** [comment]
> Hi ldkong:Thanks, I got it. Sincerely Qi

You are welcome! I am closing this issue now. Please feel free to open a new one if you have any other questions!

**Comment by ZephyRUXS** [comment]
Hi ldkong:I am sorry to bother you again. For some reasons, I cannot use email end with ".edu" or company email. I only can use my personal email address this competition.
Sincerely
Qi




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Lingdong ***@***.***&gt;; 
发送时间: 2023年1月5日(星期四) 下午3:14
收件人: ***@***.***&gt;; 
抄送: "???Jin ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ldkong1205/RoboDepth] [Competition] Question (Issue #2)





  
Hi ldkong:Thanks, I got it. Sincerely Qi
  
You are welcome! I am closing this issue now. Please feel free to open a new one if you have any other questions!

**Comment by ldkong1205** [comment]
> Hi ldkong:I am sorry to bother you again. For some reasons, I cannot use email end with ".edu" or company email. I only can use my personal email address this competition. Sincerely Qi

Hi @ZephyRUXS, don't worry! Using your personal email is fine.

We restrict the use of email domains to ensure there is no abuse of submissions in the evaluation server. For personal use only, like your situation, should be totally okay.
