### ISSUE TITLE
KITTI-C ground truth

### ISSUE THREAD

**Issue by dmn-sjk** [ldkong1205/RoboDepth#25]
Hi, great work!

I get the following error when I run `scripts/eval_kittic_MonoDepth2_mono_640x192.sh`:
```
FileNotFoundError: [Errno 2] No such file or directory: 'splits/eigen/gt_depths.npz'
```
There is no such file in the downloaded KITTI-C dataset. Is there a separate download link or a script to generate it?

**Comment by ldkong1205** [comment]
Hi @dmn-sjk, thanks for your interest in this work.

For the preparation of `gt_depths.npz`, please refer to this function from MonoDepth2: https://github.com/nianticlabs/monodepth2/blob/master/export_gt_depth.py
