### ISSUE TITLE
NYUDepth2-C is missing

### ISSUE THREAD

**Issue by Jiahao000** [ldkong1205/RoboDepth#26]
Hi @ldkong1205 ,

Thanks for sharing your great work! It seems that [NYUDepth2-C](https://github.com/ldkong1205/RoboDepth/blob/main/docs/DATA_PREPARE.md#nyudepth2-c) is still missing. Could you please release the NYUDepth2-C dataset? Very much appreciate it!

**Comment by ldkong1205** [comment]
Hi @Jiahao000, thanks for your interest in this work!

The previous NYUDepth2-C data was lost for some reason. Apology for that ...

You can generate this dataset on your side by using the following code:
https://github.com/ldkong1205/RoboDepth/blob/main/corruptions/create.py

We set a fixed random seed during the corruption simulation, thus the data should be exactly the same as the one we used before.

Feel free to reach out if you have other questions.

**Comment by Jiahao000** [comment]
Great! Thanks for your quick reply!
