### ISSUE TITLE
Looking forward to evaluation scripts on KITTI_C

### ISSUE THREAD

**Issue by debug66Yao** [ldkong1205/RoboDepth#3]
Hello, I configured according to [GET_STARTED.md](https://github.com/ldkong1205/RoboDepth/blob/main/docs/GET_STARTED.md#monodepth2-iccv19) but could not find `evaluate_kittic.sh`，I  wonder when can this script file release？Looking forward to your reply and wish you a happy new year!

**Comment by ldkong1205** [comment]
Hi @debug66Yao, thanks for your interest in this work, and sorry for the confusion.

You can use the following script as an example of the `.sh` file for running evaluations on KITTI-C, with MonoDepth2:
```shell
CUDA_VISIBLE_DEVICES=0 python3 evaluate_kittic.py \
    --load_weights_folder FOLDER_PATH \
    --eval_mono
```

Note that you will need to first download the pretrained weights of MonoDepth2 and put them into the folder `FOLDER_PATH`. You can access the weights on [this](https://github.com/nianticlabs/monodepth2#%EF%B8%8F-prediction-for-a-single-image) page.

You will also need to set the eval mode based on the model itself, for example, `eval_mono` or `eval_stereo`.

I will add these `.sh` scripts (MonoDepth2 and other models) into the codebase later. I will let you know once they are ready. Thanks!

**Comment by debug66Yao** [comment]
Ok, I get it now, thanks！
