### ISSUE TITLE
Model_zoo.md is missing

### ISSUE THREAD

**Issue by miRemid** [ldkong1205/RoboDepth#5]
I can't find the [Model_zoo.md](https://github.com/ldkong1205/RoboDepth/blob/main/docs/MODEL_ZOO.md) referenced in the README, and i also don't see the depthformer folder in the zoo directory. Are you forget to upload them？thank you

**Comment by ldkong1205** [comment]
Hi @miRemid, thanks for your reminder!

We will soonly update the results in MODEL_ZOO.md, and also upload code for fully-supervised depth estimation methods like DepthFormer.

By the way, we borrow most of the code from [Monocular-Depth-Estimation-Toolbox](https://github.com/zhyever/Monocular-Depth-Estimation-Toolbox) for our indoor depth estimation track.

Once the document and code are ready, we will let me know. Thanks!

**Comment by ldkong1205** [comment]
Hi @miRemid, we have updated some results of KITTI-C and NYUDepth2-C. You can now find them on the main page of this repository (https://github.com/ldkong1205/RoboDepth/blob/main/README.md), under section `Benchmark`.

For the code of DepthFormer: We will soonly clean up the code for this benchmark and upload it to the repository. Thanks for waiting!
